name: Generate markdown from SKOS ttl
on: workflow_dispatch
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
      - uses: actions/setup-python@v3
      - name: "Install python dependencies"
        run: |
          pip install -r requirements.txt
